-- QUESTION 1
SELECT WORKER.FIRST_NAME, WORKER.SALARY, TITLE.WORKER_TITLE
FROM WORKER
INNER JOIN TITLE ON WORKER.WORKER_ID = TITLE.WORKER_REF_ID;

-- QUESTION 2
CREATE FUNCTION get_worker_count_by_nth_highest_salary(
    N INTEGER
)
RETURNS INTEGER AS $$
DECLARE
    NTH_SALARY INTEGER;
BEGIN
    SELECT SALARY INTO NTH_SALARY
	FROM (
		SELECT DISTINCT SALARY FROM WORKER
		ORDER BY SALARY DESC LIMIT N
	) AS SUBQUERY
	ORDER BY SALARY ASC
	LIMIT 1;

	RETURN (SELECT COUNT(*) FROM WORKER WHERE SALARY = NTH_SALARY);
END;
$$
LANGUAGE plpgsql;

SELECT get_worker_count_by_nth_highest_salary(4);